"""
pages/1_Overview.py — Today's workout snapshot
===============================================
This page is the daily landing screen for Milo.  It will show the user:

- The name and exercise list for today's scheduled workout (pulled from the
  weekly plan saved in `utils/db.py`).
- A recovery input: either a manual 1–10 slider *or* an automatic score
  fetched from the WHOOP API via `utils/api.py` (WHOOP integration is pending
  API approval).
- A machine-learning recommendation generated by `utils/predict.py`, which
  takes the user's recent session history and recovery score and predicts
  whether they should increase weight this session or hold at the current
  load.

UI components planned:
    st.metric          — display today's workout name and key stats
    st.slider          — manual recovery score input (1–10)
    st.info / st.success — colour-coded recommendation box from the ML model
"""

import streamlit as st

# ---------------------------------------------------------------------------
# Page header
# ---------------------------------------------------------------------------
st.title("Overview")

# ---------------------------------------------------------------------------
# Placeholder content — real data will come from utils/db.py and
# utils/predict.py once those modules are wired up.
# ---------------------------------------------------------------------------
st.info("Coming soon — today's workout snapshot and your Milo recommendation will appear here.")
